"""
Base Circuit Generator Class
Provides common interface for all circuit generators
"""
from abc import ABC, abstractmethod
from typing import Dict, Any, List, Optional
from dataclasses import dataclass, field
from pathlib import Path
import json

from circuits.sky130.devices import Sky130Constants


@dataclass
class CircuitParameter:
    """Circuit parameter definition"""
    name: str
    value: float
    unit: str
    description: str
    min_value: Optional[float] = None
    max_value: Optional[float] = None
    
    def validate(self) -> bool:
        """Validate parameter value"""
        if self.min_value is not None and self.value < self.min_value:
            return False
        if self.max_value is not None and self.value > self.max_value:
            return False
        return True


@dataclass
class PerformanceSpec:
    """Performance specification"""
    name: str
    target: float
    unit: str
    tolerance: float = 0.1  # 10%
    measured: Optional[float] = None
    
    def is_met(self) -> bool:
        """Check if specification is met"""
        if self.measured is None:
            return False
        error = abs(self.measured - self.target) / self.target
        return error <= self.tolerance


@dataclass
class CircuitMetadata:
    """Circuit metadata"""
    name: str
    description: str
    topology: str
    technology: str = "sky130A"
    supply_voltage: float = Sky130Constants.VDD_NOMINAL
    temperature: float = Sky130Constants.TEMP_NOMINAL
    author: str = "AI Platform"
    version: str = "1.0"
    tags: List[str] = field(default_factory=list)


class BaseCircuitGenerator(ABC):
    """
    Base class for all circuit generators
    
    Provides common interface for:
    - Parameter management
    - Netlist generation
    - Performance specification
    - Metadata handling
    """
    
    def __init__(self, metadata: CircuitMetadata):
        """Initialize circuit generator"""
        self.metadata = metadata
        self.parameters: Dict[str, CircuitParameter] = {}
        self.specifications: Dict[str, PerformanceSpec] = {}
        self.devices: List[Any] = []
        
    def add_parameter(
        self,
        name: str,
        value: float,
        unit: str,
        description: str,
        min_value: Optional[float] = None,
        max_value: Optional[float] = None
    ) -> CircuitParameter:
        """Add circuit parameter"""
        param = CircuitParameter(
            name=name,
            value=value,
            unit=unit,
            description=description,
            min_value=min_value,
            max_value=max_value
        )
        self.parameters[name] = param
        return param
    
    def add_specification(
        self,
        name: str,
        target: float,
        unit: str,
        tolerance: float = 0.1
    ) -> PerformanceSpec:
        """Add performance specification"""
        spec = PerformanceSpec(
            name=name,
            target=target,
            unit=unit,
            tolerance=tolerance
        )
        self.specifications[name] = spec
        return spec
    
    def update_parameter(self, name: str, value: float) -> None:
        """Update parameter value"""
        if name in self.parameters:
            self.parameters[name].value = value
        else:
            raise ValueError(f"Parameter {name} not found")
    
    def get_parameter(self, name: str) -> float:
        """Get parameter value"""
        if name in self.parameters:
            return self.parameters[name].value
        raise ValueError(f"Parameter {name} not found")
    
    def validate_parameters(self) -> bool:
        """Validate all parameters"""
        return all(param.validate() for param in self.parameters.values())
    
    @abstractmethod
    def generate_netlist(self, output_file: str) -> str:
        """
        Generate SPICE netlist
        Must be implemented by subclasses
        """
        pass
    
    @abstractmethod
    def size_circuit(self) -> Dict[str, float]:
        """
        Auto-size circuit based on specifications
        Must be implemented by subclasses
        """
        pass
    
    def get_netlist_header(self) -> str:
        """Generate standard netlist header"""
        header = f"""* {self.metadata.name}
* {self.metadata.description}
* Topology: {self.metadata.topology}
* Technology: {self.metadata.technology}
* Generated by: {self.metadata.author}
* Version: {self.metadata.version}

.lib /opt/sky130_pdk/sky130A/libs.tech/ngspice/sky130.lib.spice tt

* Supply voltage
.param VDD={self.metadata.supply_voltage}

* Temperature
.temp {self.metadata.temperature}

"""
        return header
    
    def get_analysis_commands(
        self,
        analyses: List[str] = None
    ) -> str:
        """Generate analysis commands"""
        if analyses is None:
            analyses = ["op"]
        
        commands = ".control\nrun\n\n"
        
        # Operating point info
        if "op" in analyses:
            commands += "* Operating point\n"
            commands += "print all\n\n"
        
        # Save results
        commands += "quit\n.endc\n"
        
        return commands
    
    def export_parameters(self, filename: str) -> None:
        """Export parameters to JSON"""
        data = {
            "metadata": {
                "name": self.metadata.name,
                "description": self.metadata.description,
                "topology": self.metadata.topology,
                "technology": self.metadata.technology,
            },
            "parameters": {
                name: {
                    "value": param.value,
                    "unit": param.unit,
                    "description": param.description,
                }
                for name, param in self.parameters.items()
            },
            "specifications": {
                name: {
                    "target": spec.target,
                    "unit": spec.unit,
                    "tolerance": spec.tolerance,
                    "measured": spec.measured,
                    "met": spec.is_met() if spec.measured else None,
                }
                for name, spec in self.specifications.items()
            }
        }
        
        with open(filename, 'w') as f:
            json.dump(data, f, indent=2)
    
    def import_parameters(self, filename: str) -> None:
        """Import parameters from JSON"""
        with open(filename, 'r') as f:
            data = json.load(f)
        
        # Update parameters
        for name, param_data in data.get("parameters", {}).items():
            if name in self.parameters:
                self.parameters[name].value = param_data["value"]
    
    def summary(self) -> str:
        """Generate circuit summary"""
        lines = [
            f"\n{'='*70}",
            f"  {self.metadata.name}",
            f"{'='*70}",
            f"Description: {self.metadata.description}",
            f"Topology: {self.metadata.topology}",
            f"Technology: {self.metadata.technology}",
            f"\nParameters:",
            f"{'-'*70}",
        ]
        
        for name, param in self.parameters.items():
            lines.append(f"  {name:20s} = {param.value:12.6g} {param.unit:10s} | {param.description}")
        
        if self.specifications:
            lines.extend([
                f"\nSpecifications:",
                f"{'-'*70}",
            ])
            
            for name, spec in self.specifications.items():
                status = "✓" if spec.is_met() else "✗" if spec.measured else "?"
                measured_str = f"{spec.measured:.6g}" if spec.measured else "N/A"
                lines.append(
                    f"  [{status}] {name:15s} Target: {spec.target:10.6g} {spec.unit:10s} "
                    f"Measured: {measured_str}"
                )
        
        lines.append(f"{'='*70}\n")
        return '\n'.join(lines)
    
    def __str__(self) -> str:
        """String representation"""
        return self.summary()


# ============================================================================
# Example Usage
# ============================================================================

class ExampleAmplifier(BaseCircuitGenerator):
    """Example amplifier circuit"""
    
    def __init__(self):
        metadata = CircuitMetadata(
            name="Single-Stage Amplifier",
            description="Common-source amplifier with resistive load",
            topology="CS-Amplifier",
            tags=["amplifier", "single-stage", "basic"]
        )
        super().__init__(metadata)
        
        # Define parameters
        self.add_parameter("W", 2.0, "μm", "NMOS width", min_value=0.42, max_value=100)
        self.add_parameter("L", 0.5, "μm", "NMOS length", min_value=0.15, max_value=10)
        self.add_parameter("Rd", 10e3, "Ω", "Drain resistor", min_value=1e3, max_value=1e6)
        
        # Define specifications
        self.add_specification("gain", 10, "V/V", tolerance=0.2)
        self.add_specification("bandwidth", 1e6, "Hz", tolerance=0.3)
    
    def generate_netlist(self, output_file: str) -> str:
        """Generate amplifier netlist"""
        # Implementation would go here
        netlist = self.get_netlist_header()
        netlist += "* Circuit implementation...\n"
        netlist += self.get_analysis_commands()
        
        with open(output_file, 'w') as f:
            f.write(netlist)
        
        return output_file
    
    def size_circuit(self) -> Dict[str, float]:
        """Auto-size based on specs"""
        # Simple example - real implementation would be more complex
        target_gain = self.specifications["gain"].target
        
        # Rough estimation
        W = 2.0
        L = 0.5
        Rd = 10e3
        
        return {"W": W, "L": L, "Rd": Rd}


if __name__ == "__main__":
    # Example usage
    amp = ExampleAmplifier()
    print(amp.summary())
    
    # Size circuit
    sized_params = amp.size_circuit()
    print(f"\nSized parameters: {sized_params}")
    
    # Export
    amp.export_parameters("amplifier_params.json")
    print("✓ Parameters exported")
